# Generated by Django 5.0.4 on 2024-04-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
    ]
